import { Press_Start_2P, Pixelify_Sans } from "next/font/google";; //add fonts
import "../styles/globals.scss";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const pixelify_sans = Pixelify_Sans({
  subsets: ['latin'],
  variable: '--font-pixelify_sans',
  display: 'swap',
});

export const press_start_2p = Press_Start_2P({
  weight: ['400'],
  subsets: ['latin'],
  variable: '--font-press_start_2p',
  display: 'swap',
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${press_start_2p.variable} ${pixelify_sans.variable}`}>{children}</body>
    </html>
  );
}
